# Generated by Django 6.0.1 on 2026-02-01 09:21

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', django_jalali.db.models.jDateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
