# Generated by Django 6.0.1 on 2026-02-01 09:23

import factor.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='serial',
            field=models.CharField(default=factor.tools.serial, max_length=50),
        ),
    ]
