# Generated by Django 6.0.1 on 2026-01-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('e_serial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntExt',
            fields=[
                ('exid', models.AutoField(primary_key=True, serialize=False)),
                ('enter', models.DateTimeField(auto_now_add=True)),
                ('exit', models.DateTimeField(auto_now_add=True)),
                ('absent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
    ]
