# Generated by Django 6.0.1 on 2026-01-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_serial',
            field=models.CharField(default='tLzMRuGgrCNS7bw2cU8q', max_length=100),
        ),
    ]
