# Generated by Django 6.0.1 on 2026-01-31 06:12

import hrm.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_alter_employee_e_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_serial',
            field=models.CharField(default=hrm.tools.serial, max_length=20, unique=True),
        ),
    ]
