# Generated by Django 6.0.1 on 2026-01-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_employee_e_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='NULL_FIELD', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='NULL_FIELD', max_length=50),
        ),
    ]
