# Generated by Django 6.0.1 on 2026-01-31 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_user_employee_email_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.user'),
        ),
        migrations.AlterField(
            model_name='entext',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
    ]
