# Generated by Django 6.0.1 on 2026-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entext',
            name='enter',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entext',
            name='exit',
            field=models.DateTimeField(),
        ),
    ]
