# Generated by Django 6.0.1 on 2026-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_entext_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entext',
            name='exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
