# Generated by Django 6.0.1 on 2026-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_alter_entext_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='desktop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
