# Generated by Django 6.0.1 on 2026-01-31 15:30

import hrm.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_employee_desktop_employee_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='entext',
            name='enter_time',
            field=models.TimeField(default=hrm.tools.time),
        ),
        migrations.AddField(
            model_name='entext',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entext',
            name='enter',
            field=models.DateField(default=hrm.tools.date),
        ),
        migrations.AlterField(
            model_name='entext',
            name='exit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
