# Generated by Django 6.0.1 on 2026-01-31 15:51

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_entext_enter_time_entext_exit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entext',
            name='enter',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='entext',
            name='exit',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
