# Generated by Django 6.0.1 on 2026-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_alter_entext_enter_alter_entext_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entext',
            name='late_accept',
            field=models.BooleanField(default=False),
        ),
    ]
